name: GABORWRAIGHT
favicon: null
layout_spectrum: 0.23957
typography_spectrum: 0.77375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f6f9'
    - '#20283b'
    - '#bd3130'
    - '#0d95a5'
    - '#dcae27'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
