typography_spectrum: 0.941
color:
  brandColors:
    - '#ffffff'
    - '#b2c8dd'
    - '#5d80a8'
    - '#0b0b15'
    - '#72543c'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0478615895844996
analytics:
  google: UA-73362420-1
  facebook: null
  twitter: null
name: Gabor Wraight
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Technologist / Dad - Sharing thoughts and inspiration
purpose: []
