name: Gabor Wraight
favicon: null
layout_spectrum: 0.26564
typography_spectrum: 0.941
title: Technologist / Dad - Sharing thoughts and inspiration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73362420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#282725'
    - '#c0c1c3'
    - '#9c988c'
    - '#3367b3'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
