name: Gabor Wraight
favicon: null
layout_spectrum: 0.1507
typography_spectrum: 0.941
title: Technologist / Dad - Sharing thoughts and inspiration
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73362420-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#282725'
    - '#c0c1c3'
    - '#9c988c'
    - '#3367b3'
  brandStrength: 0
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
